// grip_build.mjs - weapon grip frames (hand space) from the baked prone poses, and the generated runtime module.
import * as THREE from 'three';
import { V } from './rig.mjs';
import { crawlPose } from './crawl.mjs';
import { fistPoint, frameM, gripFrom, packM } from './grips.mjs';

// weapon sockets (assets/characters/weapons/weapons.glb, weapon space: +Z muzzle, +Y up, origin = grip_r)
export const SOCK = {
  no4_sniper: { sling_f: V(0, -0.04, 0.45), butt: V(0, -0.06, -0.34), muzzle: V(0, 0.028, 0.83), grip_l: V(0, -0.012, 0.34) },
  thompson: { grip_l: V(0, -0.06, 0.24), butt: V(0, -0.04, -0.32), muzzle: V(0, 0.03, 0.48) },
};
const pitchFor = (from, to, dy) => {             // pitch (rad, muzzle up) so that `to` sits dy below `from`
  const d = to.clone().sub(from); let th = 0;
  for (let i = 0; i < 40; i++) th += ((d.y * Math.cos(th) + d.z * Math.sin(th)) + dy) * 0.8;
  return th;
};
const dirOf = (yaw, pitch) => V(Math.sin(yaw) * Math.cos(pitch), Math.sin(pitch), Math.cos(yaw) * Math.cos(pitch));

export function buildGrips(ctx) {
  const { R, SH } = ctx, G = {};
  // crawl, long gun: the right fist around the sling at the front swivel, the handguard over the forearm, butt dragging
  crawlPose(R, 0, 'long', SH);
  let fp = fistPoint(R, 'r').add(V(0, 0.035, 0)), yawIn = 8 * Math.PI / 180;
  let th = pitchFor(SOCK.no4_sniper.sling_f, SOCK.no4_sniper.butt, fp.y - 0.03);
  G.crawl_long = { hand: 'r', socket: 'sling_f', m: packM(gripFrom(R, 'r', frameM(fp, dirOf(yawIn, th), V(0, 1, 0)))) };
  // crawl, SMG: fist on the foregrip / barrel shroud, magazine rolled outboard (right), butt by the ribs
  th = pitchFor(SOCK.thompson.grip_l, SOCK.thompson.butt, fp.y - 0.05);
  G.crawl_smg = { hand: 'r', socket: 'grip_l', roll: -90, m: packM(gripFrom(R, 'r', frameM(fp.clone().add(V(0, -0.01, 0)), dirOf(yawIn, th), V(0, 1, 0)))) };
  // crawl, MP40: its 25 cm magazine rolled outboard stuck out sideways like a gun lying crosswise (review) - the fist
  // holds the magazine instead, the gun upright above it, pointing forward with the muzzle off the ground
  G.crawl_mp40 = { hand: 'r', at: [0, -0.15, 0.19], m: packM(gripFrom(R, 'r', frameM(fistPoint(R, 'r'), dirOf(yawIn, 0.06), V(0, 1, 0)))) };
  // crawl, knife: blade forward along the fist, flat side up, tip clear of the ground
  crawlPose(R, 0, 'knife', SH);
  const ha = R.axes('hand_r').along;
  G.crawl_knife = { hand: 'r', socket: 'grip_r', m: packM(gripFrom(R, 'r', frameM(fistPoint(R, 'r'), V(ha.x, 0, ha.z).normalize().add(V(0, 0.16, 0)), V(0, 1, 0)))) };
  Object.assign(G, ctx.grips || {});
  return G;
}

/** Source of src/art/characters/prone-grips.js. */
export function gripModule(G) {
  return `// GENERATED by tools/characters/prone/bake_prone.mjs - do not edit (CC0 project code).
// Weapon grip frames for the prone clips (docs/crawl-animation.md §3.5 / §6.3), in the space of the hand bone that
// carries the weapon: weapon = hand.matrixWorld * m * rotZ(roll) * translate(-socket). Shared by every runtime's
// weapon code (pipeline/weapons.js, commandos_b/weapons.js, guests/weapons.js, enemies/enemy_weapons.js).
import * as THREE from 'three';

export const GRIPS = ${JSON.stringify(G)};

const LONG = new Set(['kar98k', 'no4_sniper', 'harpoon_gun', 'mg34', 'mg42']);
const SMG = new Set(['thompson', 'mp40']);
const PISTOL = new Set(['colt1911', 'walther_p38', 'luger']);
/** Weapon class of a prop name: long | smg | pistol | knife | other. */
export function weaponClass(name) {
  return LONG.has(name) ? 'long' : SMG.has(name) ? 'smg' : PISTOL.has(name) ? 'pistol' : name === 'knife' ? 'knife' : 'other';
}
// prone clip -> grip per weapon name or class (missing = weapon hidden: holstered pistol, stowed tool)
const BY_CLIP = {
  crawl: { long: 'crawl_long', smg: 'crawl_smg', mp40: 'crawl_mp40' }, crawl_idle: { long: 'crawl_long', smg: 'crawl_smg', mp40: 'crawl_mp40' },
  crawl_knife: { knife: 'crawl_knife' }, crawl_unarmed: {}, crawl_idle_unarmed: {},
  prone_aim: { long: 'aim_long', smg: 'aim_smg' }, prone_shoot: { long: 'aim_long' }, prone_shoot_smg: { smg: 'aim_smg' },
  prone_pistol_aim: { pistol: 'pistol' }, prone_pistol_shoot: { pistol: 'pistol' },
  prone_turn_l: { long: 'crawl_long', smg: 'crawl_smg', mp40: 'crawl_mp40' }, prone_turn_r: { long: 'crawl_long', smg: 'crawl_smg', mp40: 'crawl_mp40' },
  // stance changes: the right fist keeps the gun at the swivel (weapon-handover.js blends it off / onto the sling)
  go_prone: { long: 'crawl_long', smg: 'crawl_smg', mp40: 'crawl_mp40' }, get_up: { long: 'crawl_long', smg: 'crawl_smg', mp40: 'crawl_mp40' },
};
/** True when the clip is one of the prone set that carries its own weapon hold. */
export const isProneHold = (clip) => !!BY_CLIP[clip];
const _cache = new Map();
/**
 * Weapon placement for a prone clip: null = not a prone-hold clip (use the runtime's own hold), {hide:true} = weapon
 * hidden (holstered / stowed), else {hand:'l'|'r', local:Matrix4} = the weapon's matrix in that hand bone's space.
 * @param {string} clip @param {string} name weapon prop name @param {Object<string,THREE.Object3D>} sockets weapon sockets
 */
export function proneGrip(clip, name, sockets = {}) {
  const by = BY_CLIP[clip]; if (!by) return null;
  const key = by[name] || by[weaponClass(name)]; if (!key) return { hide: true };
  const g = GRIPS[key], ck = key + ':' + name;
  if (!_cache.has(ck)) {
    const so = sockets[g.socket] || sockets.grip_r, s = g.at ? new THREE.Vector3().fromArray(g.at) : so && (so.isVector3 ? so : so.position);   // Object3D sockets or plain positions (enemy_weapons)
    const m = new THREE.Matrix4().fromArray(g.m);
    if (g.roll) m.multiply(new THREE.Matrix4().makeRotationZ(g.roll * Math.PI / 180));
    if (s) m.multiply(new THREE.Matrix4().makeTranslation(-s.x, -s.y, -s.z));
    _cache.set(ck, { hand: g.hand, local: m });
  }
  return _cache.get(ck);
}
`;
}
