// GENERATED by tools/characters/prone/bake_prone.mjs - do not edit (CC0 project code).
// Weapon grip frames for the prone clips (docs/crawl-animation.md §3.5 / §6.3), in the space of the hand bone that
// carries the weapon: weapon = hand.matrixWorld * m * rotZ(roll) * translate(-socket). Shared by every runtime's
// weapon code (pipeline/weapons.js, commandos_b/weapons.js, guests/weapons.js, enemies/enemy_weapons.js).
import * as THREE from 'three';

export const GRIPS = {"crawl_long":{"hand":"r","socket":"sling_f","m":[-0.94452,0.05889,0.32315,0,0.32206,-0.02742,0.94632,0,0.06459,0.99789,0.00694,0,0.01162,0.06822,0.03593,1]},"crawl_smg":{"hand":"r","socket":"grip_l","roll":-90,"m":[-0.94452,0.05889,0.32315,0,0.31738,-0.08989,0.94403,0,0.08464,0.99421,0.06621,0,0.00836,0.06784,0.02648,1]},"crawl_mp40":{"hand":"r","at":[0,-0.15,0.19],"m":[-0.94452,0.05889,0.32315,0,0.32243,-0.02154,0.94635,0,0.06269,0.99803,0.00136,0,0.00022,0.06688,0.00286,1]},"crawl_knife":{"hand":"r","socket":"grip_r","m":[-0.96015,-0.00879,0.27935,0,0.27835,-0.12048,0.95289,0,0.02528,0.99268,0.11813,0,0.00022,0.06688,0.00286,1]},"aim_long":{"hand":"l","socket":"grip_r","m":[0.23017,-0.84066,0.49021,0,0.96561,0.2599,-0.00768,0,-0.12095,0.47512,0.87157,0,0.06693,-0.00643,-0.15438,1]},"aim_smg":{"hand":"l","socket":"grip_r","m":[0.23017,-0.84066,0.49021,0,0.96561,0.2599,-0.00768,0,-0.12095,0.47512,0.87157,0,0.1157,-0.00345,-0.17218,1]},"pistol":{"hand":"r","socket":"grip_r","m":[-0.93226,0.36173,-0.00648,0,-0.31719,-0.8086,0.49554,0,0.17401,0.46403,0.86856,0,0.00022,0.06688,0.00286,1]}};

const LONG = new Set(['kar98k', 'no4_sniper', 'harpoon_gun', 'mg34', 'mg42']);
const SMG = new Set(['thompson', 'mp40']);
const PISTOL = new Set(['colt1911', 'walther_p38', 'luger']);
/** Weapon class of a prop name: long | smg | pistol | knife | other. */
export function weaponClass(name) {
  return LONG.has(name) ? 'long' : SMG.has(name) ? 'smg' : PISTOL.has(name) ? 'pistol' : name === 'knife' ? 'knife' : 'other';
}
// prone clip -> grip per weapon name or class (missing = weapon hidden: holstered pistol, stowed tool)
const BY_CLIP = {
  crawl: { long: 'crawl_long', smg: 'crawl_smg', mp40: 'crawl_mp40' }, crawl_idle: { long: 'crawl_long', smg: 'crawl_smg', mp40: 'crawl_mp40' },
  crawl_knife: { knife: 'crawl_knife' }, crawl_unarmed: {}, crawl_idle_unarmed: {},
  prone_aim: { long: 'aim_long', smg: 'aim_smg' }, prone_shoot: { long: 'aim_long' }, prone_shoot_smg: { smg: 'aim_smg' },
  prone_pistol_aim: { pistol: 'pistol' }, prone_pistol_shoot: { pistol: 'pistol' },
  prone_turn_l: { long: 'crawl_long', smg: 'crawl_smg', mp40: 'crawl_mp40' }, prone_turn_r: { long: 'crawl_long', smg: 'crawl_smg', mp40: 'crawl_mp40' },
  // stance changes: the right fist keeps the gun at the swivel (weapon-handover.js blends it off / onto the sling)
  go_prone: { long: 'crawl_long', smg: 'crawl_smg', mp40: 'crawl_mp40' }, get_up: { long: 'crawl_long', smg: 'crawl_smg', mp40: 'crawl_mp40' },
};
/** True when the clip is one of the prone set that carries its own weapon hold. */
export const isProneHold = (clip) => !!BY_CLIP[clip];
const _cache = new Map();
/**
 * Weapon placement for a prone clip: null = not a prone-hold clip (use the runtime's own hold), {hide:true} = weapon
 * hidden (holstered / stowed), else {hand:'l'|'r', local:Matrix4} = the weapon's matrix in that hand bone's space.
 * @param {string} clip @param {string} name weapon prop name @param {Object<string,THREE.Object3D>} sockets weapon sockets
 */
export function proneGrip(clip, name, sockets = {}) {
  const by = BY_CLIP[clip]; if (!by) return null;
  const key = by[name] || by[weaponClass(name)]; if (!key) return { hide: true };
  const g = GRIPS[key], ck = key + ':' + name;
  if (!_cache.has(ck)) {
    const so = sockets[g.socket] || sockets.grip_r, s = g.at ? new THREE.Vector3().fromArray(g.at) : so && (so.isVector3 ? so : so.position);   // Object3D sockets or plain positions (enemy_weapons)
    const m = new THREE.Matrix4().fromArray(g.m);
    if (g.roll) m.multiply(new THREE.Matrix4().makeRotationZ(g.roll * Math.PI / 180));
    if (s) m.multiply(new THREE.Matrix4().makeTranslation(-s.x, -s.y, -s.z));
    _cache.set(ck, { hand: g.hand, local: m });
  }
  return _cache.get(ck);
}
