"""Per-asset summary of the rework-1 changes (written into each sidecar as `rework`, reused for the report)."""
COMMON = ("new desert lib materials with real albedo breakup (limewash_worn, mud_render, mudbrick, sandstone_ochre, screed_roof, "
          "bitumen_felt, corrugated_galv, patio_flags, palm_log, canvas_camo, darj_panel); decal atlas feathered (no hard quads); "
          "interior_dark cards replaced by dim plaster / modelled interiors; AO atlas background dilated (no black mip bleed); "
          "warm sand-bounce vertex tint on sun-averted faces; KHR_mesh_quantization (normals/tangents int8, uv1 u16); effective-albedo floor (material lum >= 0.045 linear, material x vertex-colour >= 0.03) and opacity caps on near-black decals (soot 0.5, crack 0.7) so iron, tar, char, scorch and crude never render as pure-black voids; LOD2 re-tuned to ~12-15% of LOD0")
CHANGES = {
 'house_flat_white_a': "L-plan: 2-storey block + SW one-storey terrace wing, stair on the wing's EAST side (climbs N) with plastered cheek, lime coping with drip lips, square capped newel and arched storage niche; lime-coped parapets (no pipe rolls); horseshoe door with painted boarded fanlight + iron sunburst grille (no void); cracked screed roofs with lime/tar repairs, roof hatch, stair kiosk, laundry, flue; terrace jars, reed mat of drying peppers, firewood; fallen render with rubble/brick showing (raised broken rims), rain streaks under copings/spouts, damp base; sand apron blobs removed",
 'house_flat_white_b': "different plan: 2-storey block with a corbelled first-floor bay on timber joists + 3rd-storey ghorfa room, jogged one-storey annex to the east whose stair runs along its SOUTH front (climbs W, street-side cheek), ladder annex->main roof; lime copings, painted fanlight, barrel vault on the annex roof, hatch, repairs, laundry, coop; weathered worn lime-wash",
 'house_flat_white_c': "different plan: long single-storey house with a qubba dome on a square drum, two-storey tower room at the EAST end, walled forecourt with arched double gate, flagged court, vine arbour and mastaba bench; stair up the WEST gable (climbs N); blue dado, lime copings, painted fanlight, roof repairs, jars, peppers, laundry",
 'house_adobe_a': "red-brown mud/straw render (reads against the sand at 1x), eroded sloping mud skirt at the wall foot, lime-whitened door surround + gypsum patches, rain-cut rounded mud parapets (no rolls), rough palm-trunk joists barely protruding, small flush openings with palm-log lintels (no vents), exposed mud brick where render fell, cracks, rain gullies; frond arbour of individual palm fronds; mud-walled yard with palm gate posts, oven, jars, fodder, roof hatch + mud repairs",
 'house_adobe_b': "same mud language; two-storey block + store; external mud stair on the store's EAST side with plastered cheek/coping/newel/niche (no flat dark stringer); mud parapets (no merlons/vigas), palm joists, lime patches, erosion, frond arbour, oven",
 'house_adobe_c': "DIFFERENT L-plan shelled ruin: east half collapsed to stepped mud-brick wall stumps 0.5-1.7 m (brick courses in section), surviving west roof with a ragged broken edge, palm joists snapped/hanging into the room, slumped mud-brick rubble (earth mound + bonded brick fragments + broken palm beams + torn reed matting), parapet only on standing walls, fire-scorched openings, charred door, smashed jars",
 'compound_courtyard_a': "lime-coped perimeter (drip copings); skifa gate tower with modelled passage (benches, joist ceiling, paving); north range roof broken by three barrel vaults, hatch, chimney; lower arcaded portico with its own roof, paved lit gallery, joists, bench; paved courtyard with well, planters with agave, jars, trough; galvanised stable shed; worn limewash with stone showing, spalls, streaks",
 'compound_courtyard_b': "different layout: mud ksar-farm - two-tier barrel-vaulted ghorfa granary with palm-peg steps and board doors (one open), west room range with frond arbour, animal pen of palm logs, oven, fodder, beaten earth + cobbles at the well; eroded mud perimeter with merlons, mud skirt, gullies, lime patches; gate passage modelled",
 'mosque_tunis': "now ONE complete landmark (hall + courtyard + minaret, 27.9k tris / 2.2 MB); hall arches open onto a modelled hypostyle (mats, rugs, marble columns + inner arcade, painted joist ceiling, lamps) - near-black 9.3% -> ~0%; green-glazed nave gable, skylights, entry dome, repairs on the hall roof; ochre ashlar dome base + octagonal drum with blind arcades and a two-tone voussoir band; 3 m dome with 16 raised limestone ribs + brass jamour; galleries with paved floors, plank ceilings, blind-arch niches, benches; patio flags, basin water; portal with darj-wa-ktaf spandrel; high windows as grilles over dim reveals",
 'minaret_tunis': "ochre sandstone shaft with white limestone string courses, darj-wa-ktaf lozenge panels in limestone frames on all four faces + blind-arch frieze, paired arched lights with colonnettes at two levels per face (hollow shaft with newel, no black), corbelled balcony with sandstone merlons, lantern with ablaq arches, green-glazed cap + brass jamour",
 'barracks_desert_a': "veranda is now a LOWER arcaded portico with its own roof (real step, no stray parapet line), paved gallery with benches, ammo crates, lamps; main roof in cracked screed with tar expansion strips, repairs, hatch, vent stacks, water tank, radio mast with aerial, sandbagged MG nest; pilasters, moulded cornice, painted fascia band, window surrounds, clerestory grilles; flag stand-in (field-grey + Balkenkreuz, separate 'flag' node) with halyard",
 'barracks_desert_a_destroyed': "roof broken in two ragged slabs, two slab plates hinged into the room with bent rebar, modelled interior (floor, partition, bunks, lockers) under the hole - no black cards; limestone/plaster/screed/rebar/beam rubble in limestone colours; blast breaches; 14.7k tris (was 15.4k)",
 'barracks_desert_b': "sand-painted boards (no dark brown), sun-bleached towards the top; sill plate, skirting and taller concrete piers; tar-felt roof with lapped-strip battens, felt ridge roll and patches; gable louvres; porches, fire buckets, sand drifts; flag stand-in + halyard",
 'barracks_desert_b_destroyed': "roof holes open onto a modelled interior (floor boards, bunks, table, stove); charred splintered board ends round the wall breach; debris is planks, splintered studs and bent felt sheets (no stone boulders)",
 'tent_command': "canvas is a smooth-shaded 24x19 grid with catenary sag between the ridge uprights and guyed eave points, bellied walls, sod-cloth flare; painted disruptive camouflage (canvas_camo); panel seams, eave reinforcement band, grommets at the guy points; door cut into the end wall with tied flaps; modelled interior (liner, duckboards, cot, chest)",
 'tent_command_destroyed': "charred wall stubs with a burn gradient, snapped ridge pole hanging from the end uprights, curled burnt canvas shreds on the ground and hanging from the poles, ash bed, large soft scorch; no polyhedral rocks or floating black cards",
 'fuel_depot': "roof and cladding are real corrugated sheets (0.15 m profile visible at the eaves, lapped, galvanised with rusty replacements, ridge flashing); gable framing + cladding; slab expansion joints, drain grating, soft oil stains; fuel hand-pump stand with crank and hose, funnels, sand bin + fire beaters, sand drifts",
 'fuel_depot_destroyed': "blast crater (raised ejecta rim) with radial scorch; burst drums with split, peeled steel petals; blown-off sheets curled and twisted with real corrugation; surviving charred trusses holding a hanging sheet; charred broken timbers; no pink shard rubble",
 'drilling_rig': "every derrick member is angle iron (L profile) with its own UVs (no smearing), gusset plates with bolts at every joint, crown block with visible sheaves, gin pole, racking board with fingers and racked pipe stands, four guy lines to deadmen; painted red-oxide (no black); detailed drawworks (frames, drum with wraps, brake rims, chain guard, levers), engine inside the house, 24-pipe rack, pit walkway and mud lines",
 'drilling_rig_destroyed': "derrick snapped above the second panel with torn stubs and a bent hinge leg, falls SE clear of the other structures, every member buckled/kinked, crushed flat where it meets the ground; wreck iron pieces, bent corrugated sheets, crude pool at the wellhead, large scorch, fire anchors",
 'well_desert_a': "curb, coping, posts and troughs built of individual worn limestone blocks; rope-polished notches in the coping, rope grooves on the palm beam, pulley, rope coil, leather buckets; flagged apron dished to a stone drain, wet dark ground, puddle, algae line, trough water (not black); fieldstone windbreak with a mud capping (no roll)",
 'well_desert_b': "board-formed concrete chamber with a steel hatch; cast-iron pump with rings, spout and lever link; canvas tank with panel seams, straps, rim sagging between the posts and lacing; standpipe manifold with four taps over drip trays, puddles and wet sand (Capuzzo water point)",
 'wall_octagon_seg': "hand-built mud wall with vertical rain gullies (deeper at the top), eroded rounded crown (no roll), undercut where the mud meets the rubble footing; mud-brick spalls; angle-iron pickets with barbed wire (real barbs); palm-log weep spouts; decals feathered and sparse (no repeating rectangles)",
 'wall_octagon_corner': "bastion enlarged (r 1.65 m, 4.3 m) and strongly battered, eroded rounded mud merlons with embrasures, loopholes as framed slits with dim recess (no black), palm lintels, walkable top with hatch, spalls",
 'wall_octagon_gate': "piers with fieldstone bases, mud render, lime band, corbelled cap and dome; tube-frame leaves with barbed-wire mesh, strap hinges + pintles, latch with padlock; wheel ruts and worn ground through the gateway",
 'wall_octagon_breach': "breach built from stepped mud-brick courses at both broken ends (no smeared boolean faces), low stone stump in the gap, slumped mud-brick rubble mounds and knocked-out fieldstones (no icospheres, no melted shard), cut barbed wire drooping from the last pickets",
}
