#!/usr/bin/env node
/**
 * Build src/ui/europe-coast.js: Europe + North Africa coastlines for the briefing map (S15) and the map table (S06b),
 * from Natural Earth 1:50m land polygons (public domain, naturalearthdata.com). Rings are clamped to a box a little
 * larger than every map view and simplified with Douglas–Peucker, then stored as flat [lon, lat, …] arrays.
 *
 *   curl -sSLO https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_land.geojson
 *   node tools/ui/build_coast.mjs ne_50m_land.geojson
 */
import { readFileSync, writeFileSync } from 'node:fs';

const src = process.argv[2];
if (!src) throw new Error('usage: node tools/ui/build_coast.mjs <ne_50m_land.geojson>');
const BOX = { lon0: -16, lon1: 42, lat0: 22, lat1: 74 };
const TOL = 0.06; // degrees
const MIN_AREA = 0.03; // square degrees: drop islets

const gj = JSON.parse(readFileSync(src, 'utf8'));
const rings = [];
for (const f of gj.features) {
  const g = f.geometry;
  const polys = g.type === 'Polygon' ? [g.coordinates] : g.type === 'MultiPolygon' ? g.coordinates : [];
  for (const p of polys) rings.push(p[0]);
}

const inBox = ([x, y]) => x >= BOX.lon0 && x <= BOX.lon1 && y >= BOX.lat0 && y <= BOX.lat1;
const clamp = ([x, y]) => [Math.min(BOX.lon1, Math.max(BOX.lon0, x)), Math.min(BOX.lat1, Math.max(BOX.lat0, y))];

function dp(pts, tol) {
  if (pts.length < 3) return pts;
  const [a, b] = [pts[0], pts[pts.length - 1]];
  let best = -1, ix = 0;
  const dx = b[0] - a[0], dy = b[1] - a[1], L = Math.hypot(dx, dy) || 1e-9;
  for (let i = 1; i < pts.length - 1; i++) {
    const d = Math.abs(dy * pts[i][0] - dx * pts[i][1] + b[0] * a[1] - b[1] * a[0]) / L;
    if (d > best) { best = d; ix = i; }
  }
  if (best <= tol) return [a, b];
  return [...dp(pts.slice(0, ix + 1), tol).slice(0, -1), ...dp(pts.slice(ix), tol)];
}

function area(r) {
  let s = 0;
  for (let i = 0, j = r.length - 1; i < r.length; j = i++) s += (r[j][0] + r[i][0]) * (r[j][1] - r[i][1]);
  return Math.abs(s / 2);
}

const out = [];
for (const r of rings) {
  if (!r.some(inBox)) continue;
  let c = r.map(clamp);
  // collapse runs of points stuck on the clamp box into their end points
  c = c.filter((p, i) => {
    const prev = c[i - 1], next = c[i + 1];
    if (!prev || !next) return true;
    const edge = (q) => q[0] === BOX.lon0 || q[0] === BOX.lon1 || q[1] === BOX.lat0 || q[1] === BOX.lat1;
    return !(edge(prev) && edge(p) && edge(next));
  });
  if (area(c) < MIN_AREA) continue;
  // split in two halves so DP keeps closed rings stable
  const h = Math.floor(c.length / 2);
  const s = [...dp(c.slice(0, h + 1), TOL).slice(0, -1), ...dp(c.slice(h), TOL)];
  if (s.length < 4) continue;
  out.push(s.flatMap(([x, y]) => [Math.round(x * 100) / 100, Math.round(y * 100) / 100]));
}
out.sort((a, b) => b.length - a.length);
const pts = out.reduce((n, r) => n + r.length / 2, 0);
const body = out.map((r) => `  [${r.join(',')}],`).join('\n');
writeFileSync(new URL('../../src/ui/europe-coast.js', import.meta.url), `/**
 * Europe and North Africa coastlines (lon, lat pairs, flat), generated by tools/ui/build_coast.mjs from
 * Natural Earth 1:50m land (public domain). ${out.length} rings, ${pts} points. Do not edit by hand.
 * @module ui/europe-coast
 */
export const COAST = [
${body}
];
`);
console.log(`europe-coast.js: ${out.length} rings, ${pts} points`);
