import json, glob, collections
T = {}
for f in sorted(glob.glob('stage/assets/models/**/*.credits.json', recursive=True)):
    for tid, t in json.load(open(f))['textures'].items():
        if t.get('license'): T.setdefault(tid, t)
rows = collections.OrderedDict()
for mid, t in sorted(T.items()):
    src = t.get('source') or ''
    if t.get('url'):
        key = (src, t.get('id'))
        cell = f"[{src} `{t['id']}` ({t.get('name', t['id'])})]({t['url']})"
        auth = ', '.join(t.get('authors') or []) or '—'
    else:
        d = t.get('derived_from')
        dd = (f"; derived from {d['source']} `{d['id']}` (CC0)" if isinstance(d, dict) else f"; derived from {d}") if d else ''
        key = (src, dd)
        cell = src.replace('procedural (', 'Procedural (').replace('art/', 'tools/blender/') + dd
        auth = 'SHADOW SIX project (own work)'
    r = rows.setdefault(key, {'cell': cell, 'auth': auth, 'lic': t['license'], 'mids': []})
    r['mids'].append(mid)
out = ['', '### Buildings & bridges', '',
       '193 buildings and bridges (`assets/models/buildings/<theater>/`, `assets/models/bridges/`, 3 LODs each) are procedural',
       'geometry scripted in Blender with the SHADOW SIX kit (`tools/blender/`; own work, CC0). They share one texture library',
       '(`assets/textures/lib/1k` default, `2k` albedo for the ultra preset; metadata `assets/textures/lib/materials.json`).',
       'Every source is listed below; per-asset lists are in each `<asset>.credits.json`. Baked AO maps, decal/sign atlases',
       'and all lettering are own work. The review HDRI (Poly Haven `kloofendal_43d_clear_puresky`, CC0) is not shipped.',
       'Poly Haven maps were regraded, tiled and resized; procedural maps are generated by the listed scripts.', '',
       '| Library material(s) | Source | Author | Licence |', '| --- | --- | --- | --- |']
for r in rows.values():
    out.append(f"| {', '.join('`%s`' % m for m in r['mids'])} | {r['cell']} | {r['auth']} | {r['lic'].replace('-1.0', ' 1.0')} |")
open('credits_section.md', 'w').write('\n'.join(out) + '\n')
print(len(rows), 'rows', len(T), 'materials')
